<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.bivashy.lamp</groupId>
    <artifactId>vk-module</artifactId>
    <name>VKLampModule</name>
    <version>2.0.0</version>
    <properties>

        <!-- Manifest -->
        <manifest.version>${project.version}</manifest.version>

        <!-- Building -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>8</java.version>

        <!-- Dependencies -->
        <lamp.common.version>3.0.2</lamp.common.version>
        <vk-java-longpool.version>4.1.8</vk-java-longpool.version>
    </properties>

    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- Lamp Common -->
        <dependency>
            <groupId>com.github.Revxrsal.Lamp</groupId>
            <artifactId>common</artifactId>
            <version>${lamp.common.version}</version>
        </dependency>

        <!-- VK Java SDK -->
        <dependency>
            <groupId>io.github.bivashy</groupId>
            <artifactId>java-vk-bots-longpoll-api</artifactId>
            <version>${vk-java-longpool.version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.name}</finalName>
        <plugins>
            <!-- Maven compiler plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>